# Generated by Django 5.2.17 on 2026-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_tickettype_prefix_alter_tickettype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='assigning_type',
            field=models.CharField(choices=[('department', 'Department'), ('job_position', 'Job Position')], max_length=100, verbose_name='Assigning Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigning_type',
            field=models.CharField(choices=[('department', 'Department'), ('job_position', 'Job Position')], max_length=100, verbose_name='Assigning Type'),
        ),
    ]
