# Generated by Django 5.2.17 on 2026-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_candidate_referral_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstage',
            name='stage_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('applied', 'Applied'), ('test', 'Test'), ('interview', 'Interview'), ('cancelled', 'Rejected'), ('hired', 'Hired')], default='interview', max_length=20, verbose_name='Stage Type'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('applied', 'Applied'), ('test', 'Test'), ('interview', 'Interview'), ('cancelled', 'Rejected'), ('hired', 'Hired')], default='interview', max_length=20, verbose_name='Stage Type'),
        ),
    ]
