# Generated by Django 5.2 on 2026-09-07 11:38

import django.core.validators
import django.db.models.deletion
import horilla.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0013_company_setup_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('ifsc_swift', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC / SWIFT Code')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='Currency')),
                ('penny_drop_verified', models.BooleanField(default=False, verbose_name='Penny Drop Verified')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Company Bank Details',
                'verbose_name_plural': 'Company Bank Details',
            },
        ),
        migrations.CreateModel(
            name='CompanyBankVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('dropped_amount', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Dropped Amount (₹)')),
                ('drop_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10, verbose_name='Drop Status')),
                ('cashfree_reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cashfree Reference ID')),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='company_onboarding.companybankdetails', verbose_name='Bank Details')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Bank Verification Attempt',
                'verbose_name_plural': 'Bank Verification Attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('msa_reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='MSA Reference Number')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('msa_document', models.FileField(blank=True, null=True, upload_to=horilla.models.upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='MSA Document')),
                ('billing_model', models.CharField(blank=True, choices=[('management_fee', '% Management Fee'), ('per_head', 'Per-Head Fee')], max_length=20, null=True, verbose_name='Billing Model')),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated')], default='active', max_length=15, verbose_name='Status')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'MSA / Contract',
                'verbose_name_plural': 'MSA / Contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDeactivationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('invoices_reconciled', models.BooleanField(default=False)),
                ('advances_collected', models.BooleanField(default=False)),
                ('employees_transferred_or_terminated', models.BooleanField(default=False)),
                ('compliances_closed', models.BooleanField(default=False)),
                ('employees_removed_from_insurance', models.BooleanField(default=False)),
                ('employees_deactivated_from_hrms', models.BooleanField(default=False)),
                ('data_handed_over', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_records', to='base.company', verbose_name='Company')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Confirmed By')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Deactivation Record',
                'verbose_name_plural': 'Deactivation Records',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Document Tag')),
                ('file', models.FileField(upload_to=horilla.models.upload_path, verbose_name='File')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Company Document',
                'verbose_name_plural': 'Company Documents',
            },
        ),
        migrations.CreateModel(
            name='CompanyPOCContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-20 characters, optional +).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')], verbose_name='Mobile')),
                ('is_payroll_approver', models.BooleanField(default=False, verbose_name='Payroll Approver')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poc_contacts', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Point of Contact',
                'verbose_name_plural': 'Points of Contact',
            },
        ),
        migrations.CreateModel(
            name='CompanySignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('signatory_type', models.CharField(choices=[('ventura', 'Ventura'), ('client', 'Client')], max_length=20, verbose_name='Signatory Type')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Authorized Signatory',
                'verbose_name_plural': 'Authorized Signatories',
            },
        ),
        migrations.CreateModel(
            name='CompanyBrandedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('template_type', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('payslip', 'Payslip'), ('form16', 'Form 16')], max_length=20, verbose_name='Template Type')),
                ('file', models.FileField(upload_to=horilla.models.upload_path, verbose_name='File')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branded_templates', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Client-Branded Template',
                'verbose_name_plural': 'Client-Branded Templates',
                'unique_together': {('company', 'template_type')},
            },
        ),
        migrations.CreateModel(
            name='CompanyStateRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('state', models.CharField(blank=True, choices=[('01', 'Jammu and Kashmir'), ('02', 'Himachal Pradesh'), ('03', 'Punjab'), ('04', 'Chandigarh'), ('05', 'Uttarakhand'), ('06', 'Haryana'), ('07', 'Delhi'), ('08', 'Rajasthan'), ('09', 'Uttar Pradesh'), ('10', 'Bihar'), ('11', 'Sikkim'), ('12', 'Arunachal Pradesh'), ('13', 'Nagaland'), ('14', 'Manipur'), ('15', 'Mizoram'), ('16', 'Tripura'), ('17', 'Meghalaya'), ('18', 'Assam'), ('19', 'West Bengal'), ('20', 'Jharkhand'), ('21', 'Odisha'), ('22', 'Chhattisgarh'), ('23', 'Madhya Pradesh'), ('24', 'Gujarat'), ('26', 'Dadra and Nagar Haveli and Daman and Diu'), ('27', 'Maharashtra'), ('29', 'Karnataka'), ('30', 'Goa'), ('31', 'Lakshadweep'), ('32', 'Kerala'), ('33', 'Tamil Nadu'), ('34', 'Puducherry'), ('35', 'Andaman and Nicobar Islands'), ('36', 'Telangana'), ('37', 'Andhra Pradesh'), ('38', 'Ladakh')], max_length=50, null=True, verbose_name='State')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN.', regex='^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')], verbose_name='GSTIN')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_registrations', to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Place of Work / State Registration',
                'verbose_name_plural': 'Places of Work / State Registrations',
                'unique_together': {('company', 'state')},
            },
        ),
    ]
