# Generated by Django 5.2 on 2026-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybankdetails',
            name='penny_drop_verified',
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='Verification Status'),
        ),
    ]
