# Generated by Django 5.2 on 2026-09-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0002_bank_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontract',
            name='msa_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='MSA Reference Number'),
        ),
    ]
