# Generated by Django 5.2 on 2026-09-08 06:46

from django.db import migrations, models


CAPS_FIELDS = {
    "CompanyBankDetails": ["verification_status"],
    "CompanyBankVerification": ["drop_status"],
    "CompanyBrandedTemplate": ["template_type"],
    "CompanyContract": ["billing_model", "status"],
    "CompanySignatory": ["signatory_type"],
}


def uppercase_existing_values(apps, schema_editor):
    for model_name, fields in CAPS_FIELDS.items():
        Model = apps.get_model("company_onboarding", model_name)
        for field in fields:
            Model.objects.filter(**{f"{field}__isnull": False}).update(
                **{field: models.functions.Upper(field)}
            )


def lowercase_existing_values(apps, schema_editor):
    for model_name, fields in CAPS_FIELDS.items():
        Model = apps.get_model("company_onboarding", model_name)
        for field in fields:
            Model.objects.filter(**{f"{field}__isnull": False}).update(
                **{field: models.functions.Lower(field)}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0003_alter_companycontract_msa_reference_number'),
    ]

    operations = [
        migrations.RunPython(uppercase_existing_values, lowercase_existing_values),
    ]
