# Generated by Django 5.2 on 2026-09-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0004_companycontract_billing_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontract',
            name='billing_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rate for the selected Billing Model — a percentage (0-100) for % Management Fee, or a per-head currency amount for Per-Head Fee.', max_digits=10, null=True, verbose_name='Billing Value'),
        ),
        migrations.AlterField(
            model_name='companybankdetails',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=10, verbose_name='Verification Status'),
        ),
        migrations.AlterField(
            model_name='companybankverification',
            name='drop_status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10, verbose_name='Drop Status'),
        ),
        migrations.AlterField(
            model_name='companybrandedtemplate',
            name='template_type',
            field=models.CharField(choices=[('OFFER_LETTER', 'Offer Letter'), ('PAYSLIP', 'Payslip'), ('FORM16', 'Form 16')], max_length=20, verbose_name='Template Type'),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='billing_model',
            field=models.CharField(blank=True, choices=[('MANAGEMENT_FEE', '% Management Fee'), ('PER_HEAD', 'Per-Head Fee')], max_length=20, null=True, verbose_name='Billing Model'),
        ),
        migrations.AlterField(
            model_name='companycontract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='companysignatory',
            name='signatory_type',
            field=models.CharField(choices=[('VENTURA', 'Ventura'), ('CLIENT', 'Client')], max_length=20, verbose_name='Signatory Type'),
        ),
    ]
