# Generated by Django 5.2 on 2026-09-08 08:56

import company_onboarding.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0005_companycontract_billing_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetails',
            name='account_number',
            field=company_onboarding.model_fields.EncryptedCharField(blank=True, max_length=500, null=True, plain_max_length=50, verbose_name='Account Number'),
        ),
    ]
