# Generated by Django 5.2 on 2026-09-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0007_encrypt_existing_account_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='masked_account_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Masked Account Number'),
        ),
    ]
