# Generated by Django 5.2 on 2026-09-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0009_backfill_masked_account_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankverification',
            name='drop_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10, verbose_name='Drop Status'),
        ),
    ]
