# Generated by Django 5.2 on 2026-09-08 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0010_alter_companybankverification_drop_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashfreeApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('call_type', models.CharField(choices=[('VERIFY_BANK_ACCOUNT', 'Verify Bank Account'), ('REQUEST_TRANSFER', 'Request Transfer'), ('GET_TRANSFER_STATUS', 'Get Transfer Status')], max_length=30, verbose_name='Call Type')),
                ('transfer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Transfer ID')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP Status')),
                ('request_payload', models.JSONField(blank=True, null=True, verbose_name='Request Payload')),
                ('response_payload', models.JSONField(blank=True, null=True, verbose_name='Response Payload')),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashfree_logs', to='company_onboarding.companybankdetails', verbose_name='Bank Details')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashfree_logs', to='company_onboarding.companybankverification', verbose_name='Verification Attempt')),
            ],
            options={
                'verbose_name': 'Cashfree API Log',
                'verbose_name_plural': 'Cashfree API Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
