# Generated by Django 5.2 on 2026-09-08 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0011_cashfreeapilog'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybankdetails',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Used as the Cashfree beneficiary name for bank verification.', max_length=100, null=True, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='companybankdetails',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Used as the Cashfree beneficiary phone for bank verification.', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-20 characters, optional +).', regex='^\\+?[\\d\\s\\-\\(\\)]{7,20}$')], verbose_name='Contact Number'),
        ),
    ]
