# Generated by Django 5.2 on 2026-09-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0012_companybankdetails_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfreeapilog',
            name='call_type',
            field=models.CharField(choices=[('VERIFY_BANK_ACCOUNT', 'Verify Bank Account'), ('GET_BENEFICIARY', 'Get Beneficiary'), ('CREATE_BENEFICIARY', 'Create Beneficiary'), ('REQUEST_TRANSFER', 'Request Transfer'), ('GET_TRANSFER_STATUS', 'Get Transfer Status')], max_length=30, verbose_name='Call Type'),
        ),
    ]
