# Generated by Django 5.2 on 2026-09-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_onboarding', '0013_alter_cashfreeapilog_call_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankdetails',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='Verification Status'),
        ),
    ]
