# Generated by Django 5.2 on 2026-09-24 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0016_seed_default_export_permission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False,
                        help_text="Generated from the company name. Used in the SSO login URL.",
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        default="Single Sign-On",
                        help_text='Shown on the login page, e.g. "Sign in with Okta".',
                        max_length=100,
                        verbose_name="Button label",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Enabled"),
                ),
                (
                    "issuer",
                    models.URLField(
                        help_text="The OIDC issuer URL, e.g. https://acme.okta.com",
                        verbose_name="Issuer",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(max_length=255, verbose_name="Client ID"),
                ),
                (
                    "_client_secret",
                    models.TextField(
                        db_column="client_secret", verbose_name="Client secret"
                    ),
                ),
                (
                    "authorization_endpoint",
                    models.URLField(
                        blank=True, verbose_name="Authorization endpoint (override)"
                    ),
                ),
                (
                    "token_endpoint",
                    models.URLField(
                        blank=True, verbose_name="Token endpoint (override)"
                    ),
                ),
                (
                    "jwks_uri",
                    models.URLField(blank=True, verbose_name="JWKS URI (override)"),
                ),
                (
                    "scopes",
                    models.CharField(
                        default="openid email profile",
                        max_length=255,
                        verbose_name="Scopes",
                    ),
                ),
                (
                    "skip_2fa_for_sso",
                    models.BooleanField(
                        default=True,
                        help_text="The identity provider is presumed to already enforce its own MFA. Turn this off to also require Horilla's email OTP after SSO login.",
                        verbose_name="Skip local 2FA for SSO sessions",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_provider",
                        to="base.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_modified_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "OIDC Provider",
                "verbose_name_plural": "OIDC Providers",
            },
        ),
    ]
