# Generated by Django 5.2.17 on 2026-10-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_assetservicerequest_assetservicerequestnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='return_status',
            field=models.CharField(blank=True, choices=[('Minor damage', 'Minor damage'), ('Major damage', 'Major damage'), ('Healthy', 'Healthy'), ('Lost', 'Lost')], max_length=30, null=True, verbose_name='Return Status'),
        ),
    ]
