# Generated by Django 5.2.17 on 2026-10-03 11:00

import django.db.models.deletion
import payroll.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_seed_default_export_permission'),
        ('employee', '0008_alter_employee_options'),
        ('payroll', '0009_encashmentgeneralsettings_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='basic_pay', max_length=32)),
                ('condition', models.CharField(choices=[('equal', 'Equal (==)'), ('notequal', 'Not Equal (!=)'), ('lt', 'Less Than (<)'), ('gt', 'Greater Than (>)'), ('le', 'Less Than or Equal To (<=)'), ('ge', 'Greater Than or Equal To (>=)'), ('range', 'Range')], default='gt', max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('start_range', models.FloatField(blank=True, null=True)),
                ('end_range', models.FloatField(blank=True, null=True)),
                ('component_code', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='allowance',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short uppercase name other components can refer to, e.g. BASIC or HRA. Leave blank if nothing needs to reference this one.', max_length=32, validators=[payroll.models.models.component_code_validator], verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='formula',
            field=models.TextField(blank=True, default='', help_text="Expression over other components' codes, e.g. (BASIC + DA) * 0.12", verbose_name='Formula'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='if_component_code',
            field=models.CharField(blank=True, default='', help_text='The component this rule looks at. It must be worked out before this one, so give it a lower sequence.', max_length=32, verbose_name='Which component'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_basic_pay',
            field=models.BooleanField(default=False, help_text="Use this earning as the employee's basic pay when their contract has no wage. If the contract does state a wage, that wins and this earning is not paid — otherwise basic would be counted twice.", verbose_name='This is basic pay'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='allowance',
            name='percentage_of_code',
            field=models.CharField(blank=True, default='', help_text='Code of the component this percentage is taken from.', max_length=32, verbose_name='Percentage of'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Evaluation order — lower runs first. A component can only use the value of one that runs before it.', verbose_name='Sequence'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='system_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='contract',
            name='daily_leave_amount_base',
            field=models.CharField(choices=[('wage', 'Basic pay'), ('monthly_ctc', 'Monthly CTC'), ('gross_pay', 'Gross pay')], default='wage', help_text='Which figure a day of unpaid leave is a share of. Gross pay is only known after the earnings are worked out, so choosing it defers the deduction: basic pay is left whole and loss of pay comes off afterwards, instead of being taken out of basic first.', max_length=20, verbose_name='Daily Leave Amount From'),
        ),
        migrations.AddField(
            model_name='contract',
            name='daily_leave_amount_divisor',
            field=models.CharField(choices=[('working_days', 'Working days in the month'), ('calendar_days', 'Calendar days in the month')], default='calendar_days', help_text='Working days makes each unpaid day cost more: a 44,000 wage over 22 working days is 2,000 a day, over 30 calendar days it is 1,467. Calendar days is the default for a new contract.', max_length=20, verbose_name='Daily Leave Amount Divided By'),
        ),
        migrations.AddField(
            model_name='contract',
            name='hourly_wage',
            field=models.FloatField(blank=True, help_text='Pay for one hour. Used when Wage Type is Hourly, multiplied by the hours actually worked. Leave empty to use Basic Salary as the hourly rate instead.', null=True, verbose_name='Hourly wage'),
        ),
        migrations.AddField(
            model_name='contract',
            name='loss_of_pay_is_pretax',
            field=models.BooleanField(default=True, help_text='On: unpaid days come out of the figure tax is worked out on, so the employee is not taxed on pay they did not receive. Off: they are taxed as though they had been paid it.', verbose_name='Loss Of Pay Is Pre-Tax'),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_ctc',
            field=models.FloatField(blank=True, help_text='The total monthly cost to company. Only used by a CTC Down salary structure, which divides it into components. Leave empty to divide up the wage above instead.', null=True, verbose_name='Monthly CTC'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Short uppercase name other components can refer to, e.g. BASIC or HRA. Leave blank if nothing needs to reference this one.', max_length=32, validators=[payroll.models.models.component_code_validator], verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='employer_basis',
            field=models.CharField(blank=True, choices=[('rate', 'A percentage of the same figure'), ('formula', 'Custom formula')], default='rate', help_text="How the employer's share is worked out. A percentage uses the same figure the deduction is based on.", max_length=16, verbose_name='Employer contribution'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='employer_formula',
            field=models.TextField(blank=True, default='', help_text="Expression over other components' codes, e.g. (BASIC + DA) * 0.0367", verbose_name='Employer formula'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='formula',
            field=models.TextField(blank=True, default='', help_text="Expression over other components' codes, e.g. (BASIC + DA) * 0.12", verbose_name='Formula'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='if_component_code',
            field=models.CharField(blank=True, default='', help_text='The component this rule looks at. It must be worked out before this one, so give it a lower sequence.', max_length=32, verbose_name='Which component'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='percentage_of_code',
            field=models.CharField(blank=True, default='', help_text='Code of the component this percentage is taken from.', max_length=32, verbose_name='Percentage of'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Evaluation order — lower runs first. A component can only use the value of one that runs before it.', verbose_name='Sequence'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='system_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='filingstatus',
            name='cess_percent',
            field=models.FloatField(default=0.0, help_text='Added on top of the computed tax, as a percentage of it.', verbose_name='Cess / surcharge (%)'),
        ),
        migrations.AddField(
            model_name='filingstatus',
            name='rebate_income_limit',
            field=models.FloatField(blank=True, help_text='If yearly income after the standard deduction is at or below this, the rebate below is applied. Leave blank for no rebate.', null=True, verbose_name='Rebate income limit'),
        ),
        migrations.AddField(
            model_name='filingstatus',
            name='rebate_max_amount',
            field=models.FloatField(blank=True, help_text='The most tax the rebate can cancel out. Tax never goes below zero.', null=True, verbose_name='Maximum rebate'),
        ),
        migrations.AddField(
            model_name='filingstatus',
            name='standard_deduction',
            field=models.FloatField(default=0.0, help_text='Subtracted from yearly income before tax is worked out. 0 for none.', verbose_name='Standard deduction'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='daily_leave_amount_base',
            field=models.CharField(choices=[('wage', 'Basic pay'), ('monthly_ctc', 'Monthly CTC'), ('gross_pay', 'Gross pay')], default='wage', help_text='Which figure a day of unpaid leave is a share of. Gross pay is only known after the earnings are worked out, so choosing it defers the deduction: basic pay is left whole and loss of pay comes off afterwards, instead of being taken out of basic first.', max_length=20, verbose_name='Daily Leave Amount From'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='daily_leave_amount_divisor',
            field=models.CharField(choices=[('working_days', 'Working days in the month'), ('calendar_days', 'Calendar days in the month')], default='calendar_days', help_text='Working days makes each unpaid day cost more: a 44,000 wage over 22 working days is 2,000 a day, over 30 calendar days it is 1,467. Calendar days is the default for a new contract.', max_length=20, verbose_name='Daily Leave Amount Divided By'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='hourly_wage',
            field=models.FloatField(blank=True, help_text='Pay for one hour. Used when Wage Type is Hourly, multiplied by the hours actually worked. Leave empty to use Basic Salary as the hourly rate instead.', null=True, verbose_name='Hourly wage'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='loss_of_pay_is_pretax',
            field=models.BooleanField(default=True, help_text='On: unpaid days come out of the figure tax is worked out on, so the employee is not taxed on pay they did not receive. Off: they are taxed as though they had been paid it.', verbose_name='Loss Of Pay Is Pre-Tax'),
        ),
        migrations.AddField(
            model_name='historicalcontract',
            name='monthly_ctc',
            field=models.FloatField(blank=True, help_text='The total monthly cost to company. Only used by a CTC Down salary structure, which divides it into components. Leave empty to divide up the wage above instead.', null=True, verbose_name='Monthly CTC'),
        ),
        migrations.AddField(
            model_name='salarystructure',
            name='structure_mode',
            field=models.CharField(choices=[('gross_up', 'Gross Up — the wage is basic pay, allowances add to it'), ('ctc_down', 'CTC Down — the wage is the gross, components divide it')], default='gross_up', help_text="Gross Up: the contract wage IS basic pay, and allowances are added on top of it to reach gross. Gross is therefore only known once every component has run, so nothing can be defined as a percentage of it. CTC Down: the contract wage IS the gross, and the components divide it up. Because the total is known before anything runs, a component can say 'basic is 50% of gross' — one of them needs the code BASIC, and a balance component absorbs whatever is left.", max_length=20, verbose_name='Structure mode'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='based_on',
            field=models.CharField(blank=True, choices=[('basic_pay', 'Basic Pay'), ('component', 'Percentage of Another Component'), ('formula', 'Custom Formula'), ('balance', 'Balance of CTC'), ('children', 'Children'), ('overtime', 'Regular Overtime'), ('week_off_overtime', 'Week Off Overtime'), ('holiday_overtime', 'Holiday Overtime'), ('shift_id', 'Shift'), ('work_type_id', 'Work Type'), ('attendance', 'Attendance')], default='basic_pay', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='if_choice',
            field=models.CharField(choices=[('basic_pay', 'Basic pay'), ('ctc', 'Cost to company'), ('component', 'Another component')], default='basic_pay', max_length=32),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='maximum_unit',
            field=models.CharField(choices=[('month_calendar_days', "A month's worth, split by calendar days"), ('month_working_days', "A month's worth, split by working days"), ('per_working_day', 'An amount for each working day'), ('full_period', 'A flat amount, the same in every pay period')], default='month_calendar_days', help_text="What the figures above are quoted per — both a fixed amount and any ceiling. A month's worth is shared out across a part-month period, so ten working days of a twenty-two working day month gives ten twenty-seconds of it. A flat amount is the same in every period, however long. Percentages are not affected: they already follow the period through whatever they are a percentage of.", max_length=20, null=True, verbose_name='This amount is'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='calculate_daily_leave_amount',
            field=models.BooleanField(default=True, help_text='On: one unpaid day costs Daily Leave Amount From ÷ Daily Leave Amount Divided By, both set below. Off: it costs the flat Deduction For One Leave Amount typed in instead. Either way, Deduct Leave From Basic Pay decides whether it comes off basic pay directly or shows as its own deduction, and Loss Of Pay Is Pre-Tax decides whether it also reduces what tax is worked out on.', verbose_name='Calculate Daily Leave Amount'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deduct_leave_from_basic_pay',
            field=models.BooleanField(default=True, help_text='On: unpaid days are taken off basic pay before gross is built, so nothing appears as a separate deduction. Off: basic pay is left whole and loss of pay is deducted afterwards — which also means it does not reduce taxable gross.', verbose_name='Take Loss Of Pay Off Basic Pay'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='wage',
            field=models.FloatField(default=0, help_text='Basic pay under a Gross Up structure. Under a CTC Down structure this is the monthly cost to company instead, and basic pay is worked out from a component of that structure. The unit follows Wage Type: a monthly figure, a day rate, or an hourly rate.', null=True, verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='based_on',
            field=models.CharField(blank=True, choices=[('basic_pay', 'Basic Pay'), ('gross_pay', 'Gross Pay'), ('taxable_gross_pay', 'Taxable Gross Pay'), ('net_pay', 'Net Pay'), ('component', 'Percentage of Another Component'), ('formula', 'Custom Formula')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='if_choice',
            field=models.CharField(choices=[('basic_pay', 'Basic pay'), ('ctc', 'Cost to company'), ('component', 'Another component'), ('gross_pay', 'Gross pay'), ('taxable_gross_pay', 'Taxable gross pay')], default='basic_pay', max_length=32),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='maximum_unit',
            field=models.CharField(choices=[('month_calendar_days', "A month's worth, split by calendar days"), ('month_working_days', "A month's worth, split by working days"), ('per_working_day', 'An amount for each working day'), ('full_period', 'A flat amount, the same in every pay period')], default='month_calendar_days', help_text="What the figures above are quoted per — both a fixed amount and any ceiling. A month's worth is shared out across a part-month period, so ten working days of a twenty-two working day month gives ten twenty-seconds of it. A flat amount is the same in every period, however long. Percentages are not affected: they already follow the period through whatever they are a percentage of.", max_length=20, null=True, verbose_name='This amount is'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='calculate_daily_leave_amount',
            field=models.BooleanField(default=True, help_text='On: one unpaid day costs Daily Leave Amount From ÷ Daily Leave Amount Divided By, both set below. Off: it costs the flat Deduction For One Leave Amount typed in instead. Either way, Deduct Leave From Basic Pay decides whether it comes off basic pay directly or shows as its own deduction, and Loss Of Pay Is Pre-Tax decides whether it also reduces what tax is worked out on.', verbose_name='Calculate Daily Leave Amount'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='deduct_leave_from_basic_pay',
            field=models.BooleanField(default=True, help_text='On: unpaid days are taken off basic pay before gross is built, so nothing appears as a separate deduction. Off: basic pay is left whole and loss of pay is deducted afterwards — which also means it does not reduce taxable gross.', verbose_name='Take Loss Of Pay Off Basic Pay'),
        ),
        migrations.AlterField(
            model_name='historicalcontract',
            name='wage',
            field=models.FloatField(default=0, help_text='Basic pay under a Gross Up structure. Under a CTC Down structure this is the monthly cost to company instead, and basic pay is worked out from a component of that structure. The unit follows Wage Type: a monthly figure, a day rate, or an hourly rate.', null=True, verbose_name='Basic Salary'),
        ),
        migrations.AddField(
            model_name='allowance',
            name='apply_conditions',
            field=models.ManyToManyField(blank=True, editable=False, related_name='%(class)s_set', to='payroll.applycondition'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='apply_conditions',
            field=models.ManyToManyField(blank=True, editable=False, related_name='%(class)s_set', to='payroll.applycondition'),
        ),
        migrations.CreateModel(
            name='PayPeriodSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('boundary', models.CharField(choices=[('calendar_month', 'Calendar month (1st to last day)')], default='calendar_month', help_text='How a pay period is bounded. Cut-off cycles such as the 26th to the 25th are not yet supported: the engine counts working days by calendar month, so a period crossing a month boundary would prorate against the wrong one.', max_length=20, verbose_name='Period Runs')),
                ('pay_day_offset', models.PositiveIntegerField(default=0, help_text='Days after the period ends that people are actually paid. Zero means the last day of the period. This is a date on the run, not something the engine calculates with.', verbose_name='Pay Day')),
                ('input_cutoff_days', models.PositiveIntegerField(default=0, help_text='Days before the period ends after which attendance and leave changes are not expected to affect the run. Advisory: it is shown on the run, and nothing is blocked by it.', verbose_name='Input Cut-off')),
                ('company_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Pay Period Settings',
                'verbose_name_plural': 'Pay Period Settings',
            },
        ),
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('batch_name', models.CharField(max_length=150, verbose_name='Batch name')),
                ('period_start', models.DateField(verbose_name='Period start')),
                ('period_end', models.DateField(verbose_name='Period end')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Pay date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('employee_count', models.PositiveIntegerField(default=0, editable=False)),
                ('processed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('generated_count', models.PositiveIntegerField(default=0, editable=False)),
                ('failed_count', models.PositiveIntegerField(default=0, editable=False)),
                ('flagged_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Flagged (net zero or capped)')),
                ('total_gross', models.FloatField(default=0, editable=False)),
                ('total_deductions', models.FloatField(default=0, editable=False)),
                ('total_net', models.FloatField(default=0, editable=False)),
                ('total_employer', models.FloatField(default=0, editable=False)),
                ('progress_state', models.CharField(choices=[('pending', 'Not started'), ('running', 'Generating'), ('done', 'Finished'), ('failed', 'Failed')], default='pending', editable=False, max_length=20)),
                ('last_error', models.TextField(blank=True, default='', editable=False)),
                ('company_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_batches', to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('created_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_batches', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Payroll Batch',
                'verbose_name_plural': 'Payroll Batches',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicalpayslip',
            name='payroll_batch',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payroll.payrollbatch'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_batch',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='payroll.payrollbatch'),
        ),
        migrations.CreateModel(
            name='PayrollBatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('done', 'Generated'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='queued', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_batch_lines', to='employee.employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('payroll_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollbatch')),
                ('payslip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_lines', to='payroll.payslip')),
            ],
            options={
                'verbose_name': 'Payroll Batch Line',
                'verbose_name_plural': 'Payroll Batch Lines',
                'ordering': ['employee_id__employee_first_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='payrollbatch',
            index=models.Index(fields=['status', '-period_end'], name='payroll_batch_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollbatchline',
            unique_together={('payroll_batch', 'employee_id')},
        ),
    ]
