# Generated by Django 5.2 on 2026-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_applycondition_allowance_code_allowance_formula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filingstatus',
            name='filing_status',
            field=models.CharField(max_length=100, verbose_name='Filing status'),
        ),
    ]
