# Generated by Django 5.2 on 2026-09-07 11:38

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_companyleaves_company_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('change_status_company', 'Can change company status (hold/deactivate/reinstate)')], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='foreign_tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Foreign Tax ID'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=15, verbose_name='Invoice Cycle'),
        ),
        migrations.AddField(
            model_name='company',
            name='ldc_applied',
            field=models.BooleanField(default=False, verbose_name='Lower Deduction Certificate (LDC) Applied'),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Registered entity name, as per PAN/CIN.', max_length=250, null=True, verbose_name='Legal Name'),
        ),
        migrations.AddField(
            model_name='company',
            name='overdue',
            field=models.BooleanField(default=False, editable=False, verbose_name='Overdue'),
        ),
        migrations.AddField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN (format: AAAAA9999A).', regex='^[A-Z]{5}[0-9]{4}[A-Z]$')], verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='company',
            name='require_payroll_signoff',
            field=models.BooleanField(default=False, verbose_name='Require Payroll Sign-off'),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('on_hold', 'On Hold'), ('deactivated', 'Deactivated')], default='onboarding', max_length=15, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_country',
            field=models.CharField(blank=True, choices=[('india', 'India'), ('foreign', 'Foreign')], help_text='Decides whether PAN or Foreign Tax ID applies. Locks once the client becomes Active.', max_length=10, null=True, verbose_name='Tax & Registration Country'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('pan__isnull', False)), fields=('pan',), name='unique_company_pan'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('foreign_tax_id__isnull', False)), fields=('foreign_tax_id',), name='unique_company_foreign_tax_id'),
        ),
    ]
