# Generated by Django 5.2 on 2026-09-08 06:46

from django.db import migrations, models


def uppercase_existing_values(apps, schema_editor):
    Company = apps.get_model("base", "Company")
    Company.objects.filter(status__isnull=False).update(status=models.functions.Upper("status"))
    Company.objects.filter(invoice_cycle__isnull=False).update(
        invoice_cycle=models.functions.Upper("invoice_cycle")
    )
    Company.objects.filter(tax_country__isnull=False).update(
        tax_country=models.functions.Upper("tax_country")
    )


def lowercase_existing_values(apps, schema_editor):
    Company = apps.get_model("base", "Company")
    Company.objects.filter(status__isnull=False).update(status=models.functions.Lower("status"))
    Company.objects.filter(invoice_cycle__isnull=False).update(
        invoice_cycle=models.functions.Lower("invoice_cycle")
    )
    Company.objects.filter(tax_country__isnull=False).update(
        tax_country=models.functions.Lower("tax_country")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_company_setup_fields'),
    ]

    operations = [
        migrations.RunPython(uppercase_existing_values, lowercase_existing_values),
    ]
