# Generated by Django 5.2 on 2026-09-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_company_invoice_cycle_alter_company_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half-Yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=15, verbose_name='Invoice Cycle'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('DEACTIVATED', 'Deactivated')], default='ONBOARDING', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_country',
            field=models.CharField(blank=True, choices=[('INDIA', 'India'), ('FOREIGN', 'Foreign')], help_text='Decides whether PAN or Foreign Tax ID applies. Locks once the client becomes Active.', max_length=10, null=True, verbose_name='Tax & Registration Country'),
        ),
    ]
