# Generated by Django 5.2.17 on 2026-10-03 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_attendance_date_idx_and_more'),
        ('employee', '0008_alter_employee_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummaryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('present', models.FloatField(blank=True, help_text='Days present. Half days count as 0.5.', null=True, verbose_name='Present')),
                ('paid_leave', models.FloatField(blank=True, null=True, verbose_name='Paid Leave')),
                ('unpaid_leave', models.FloatField(blank=True, null=True, verbose_name='Unpaid Leave')),
                ('absent', models.FloatField(blank=True, null=True, verbose_name='Absent')),
                ('note', models.CharField(blank=True, default='', help_text='Why the counted figures were replaced.', max_length=255, verbose_name='Reason')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_overrides', to='employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Attendance Summary Override',
                'verbose_name_plural': 'Attendance Summary Overrides',
                'unique_together': {('employee_id', 'from_date', 'to_date')},
            },
        ),
    ]
